# Generated by Django 2.2.20 on 2021-04-08 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата поста'),
        ),
    ]
